[tool.briefcase]
project_name = "Hacker's Toolkit"
bundle = "eu.cafehaine.hackers-toolkit"
version = "0.0.1"
url = "https://github.com/cafehaine/hackers-toolkit"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'CaféHaine'
author_email = "kilian.guillaume@gmail.com"

[tool.briefcase.app.hackers-toolkit]
formal_name = "Hacker's Toolkit"
description = "A set of tools for developers and hackers."
icon = "src/hackers_toolkit/resources/hackers-toolkit"
sources = ['src/hackers_toolkit']
requires = []


[tool.briefcase.app.hackers-toolkit.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.hackers-toolkit.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.hackers-toolkit.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.hackers-toolkit.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.hackers-toolkit.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
